title: 测试标题
author: SimonXu
email: simon.xu72@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  空白的描述内容
# social links
twitter_username: simon_xu72
github_username:  simonxu72

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
